### ISSUE TITLE
Automated release steps from celo-blockchain `release/*` branches

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-blockchain#1056]
* [ ] Refactor build process to eliminate use of manual celo-node image builds (KR2)
* [x] Apply protections to `release/*` branches on Github
* [x] Create automated build pipeline for Geth binaries
* [ ] Complete integrations for nightly client sync testing
