### ISSUE TITLE
Create an open-source package of monitoring and alerting configurations

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-blockchain#1062]
- [ ] Create an open-source package of Grafana configurations for a basic validator dashboard 

- [ ] Create an open-source package of Prometheus Alert manager for basic validator alerting (KR6)

- [ ] Refactor metrics names to be Prometheus labels (KR6)
