### ISSUE TITLE
Zero Downtime Validator Hotswaps

### ISSUE THREAD

**Issue by trianglesphere** [celo-org/celo-blockchain#1152]
This is tracking progress on the hot swap approach to zero downtime upgrades. We've also started work on making the lookback window (how long before downtime hits) governable.

- [x] Multi-validator support in proxies  me(`trianglesphere/simple_mv`)
  - Code written. Blocked on debugging proxies that timeout when connected to boot nodes (always for certain proxies) / other nodes (occasionally for random proxies)

**Hot swapping validators**. (Needs multi-validator & multi proxy)
- [x] Start/stop RPC 
- [x] Saving primary / replica state
- [x] e2e tests
- [x] unit tests
- [x] Documentation
