### ISSUE TITLE
Release 1.5.0

### ISSUE THREAD

**Issue by trianglesphere** [celo-org/celo-blockchain#1786]
## Tasks needed to release 1.5.0

- [ ] Alfajores block number
- [ ] Mainnet block number
- [ ] Fix light client (@gastonponti to add issue / PR)
- [x] Enable celo typed transactions in the personal RPC stack (#1771)
- [x] Fix JSON (#1789 )
