### ISSUE TITLE
Improve celo-blockchain tooling (linting, gosec, CI)

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-blockchain#848]
Get1.9 uses [golangci-lint](https://github.com/golangci/golangci-lint) which provides several linting tools we can use to improve our code.

Things to do:

 - [x] Investigate linters available and activate them
 - [x] Document/Share with team how to activate linter with vscode (& other editors)
 - [x] Fix linting issues
 - [x] Investigate security related linters
 - [x] Check Trail of Bits audit doc for suggested linters
