### ISSUE TITLE
Fix known celo-blockchain issues

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-blockchain#899]
- [ ] Ignore preprepare: https://github.com/celo-org/celo-blockchain/issues/808
- [ ] Slow discovery:  https://github.com/celo-org/celo-blockchain/issues/929
- [ ] Long epoch blocks when contracts not deployed: https://github.com/celo-org/celo-blockchain/issues/928

**Comment by nategraf** [comment]
This tracking issue is no longer needed.
