### ISSUE TITLE
Multi-proxy

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-blockchain#903]
**Expected Behavior**

A validator should be able to run multiple proxies.

Additionally, the following should be completed.

- [x] Modify helm charts to support multiple proxies
- [ ] Create testing suite for multiproxy
- [ ] Integrate celostats with multi proxy 
- [ ] Manual Testing 
- [ ] Update documentation "How to run a validator with multiproxy"
- [ ] Plan Communcation for this

**Current Behavior**

A validator can only run with one proxy.
