### ISSUE TITLE
Internal audit of Announce, discovery, proxies

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-blockchain#911]
Work in pairs, or divide-and-conquer.

Goal is to produce a brief document we can walk-through as a group that covers the following: 

- [ ] How does this work?
- [ ] What are the dependencies? 
- [ ] What design docs or specs cover this feature? Any gaps? Is the spec wrong, or the implementation?
- [ ] Are there areas missing unit tests? 
- [ ] What e2e tests cover this? What could be added?
- [ ] Are inputs validated?
- [ ] Are parameters and constants set sensibly?
- [ ] If we discover a serious issue, how many hrs to a full fix inc data recovery?
- [ ] What is the path for upgrading or changing this feature (e.g governance, backwards-compatible validator upgrade, hard fork, ..)?  Does this difficulty match the quality and completeness?
- [ ] How could this be attacked?
- [ ] Are the user docs correct and complete? Links to code?

Share document, then comment on the doc, then let's have the walkthrough meeting before end of Sprint.

**Comment by jcortejoso** [comment]
https://docs.google.com/document/d/1YzH7NczCtCRPiqGUumKUTrGj1lsNdWE9ILsfj_ydYIg/edit#heading=h.aem24wibg9rc

**Comment by kevjue** [comment]
@jcortejoso - Can this be closed?
