### ISSUE TITLE
Blockscout GraphQL API extensions

### ISSUE THREAD

**Issue by diminator** [celo-org/celo-blockchain#912]
### URL Attestations
- [ ] complete flow for URL attestations, see #2787
- [ ] crawl attestations and populate in blockscout-postgres
- [ ] expose attestations to graphql API

### Phone Number Privacy 
- [ ] stake/balance over time calculation, info to be provided by @kobigurk
